### ISSUE TITLE
API Access?

### ISSUE THREAD

**Issue by tleen** [northernbeacheswebsites/wp-gotowebinar#1]
Glad you put the source back up. Already forked it in hope I can help sometimes!

We need a paid account to use the API? Is there some sort of dev api we can use to develop against without needing a paid account?

**Comment by northernbeacheswebsites** [comment]
Hey, yeah I found a way to work with Github efficiently, so I hope to keep it updated on here. That's a very good question. I have always been lucky and had access to a paid account. I looked into the FAQ here: https://goto-developer.logmeininc.com/faq-page#n3868 and it looks like you can get a user account setup for particular products on a trial. It looks like the API would work for the trial account.

**Comment by tleen** [comment]
Great thanks. If there are things you are looking to do with the plugin perhaps put in the issues and when I find some spare cycles I can throw in.

**Comment by northernbeacheswebsites** [comment]
Awesome, sounds good :) Definitely appreciate your involvement!
